name: runtests

on: [push, pull_request]

jobs:
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.8', '1.9']
        os: [ubuntu-latest]
        provider: ['mkl', 'fftw']
      fail-fast: false
    env:
      PYTHON: python3

    steps:
      - uses: actions/checkout@v1.0.0
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - run: >
          sudo apt-get install --no-install-recommends gfortran python3-setuptools python3-wheel
          && pip3 install camb healpy
          && julia -e 'using Pkg; Pkg.add(url="https://github.com/EthanAnderes/CirculantCov.jl")'
          && julia --project .github/set_fftw_provider.jl "${{ matrix.provider }}"
      - uses: julia-actions/julia-runtest@v1
        timeout-minutes: 30